### ISSUE TITLE
フォントファイルへのパスどちらが正解問題 font or fonts

### ISSUE THREAD

**Issue by 8bitodyssey** [megane9988/wpdbook2016summer#1]
styles.css からのフォントへのパスは ./assets/fonts/ で記述されていますが、
ファイル構成上 assets フォルダの中にあるのは font フォルダとなっています。

にもかかわらずなぜか読み込まれている genericons... 
フォントファイルへのパスはどちらが正解？
そして genericons はなぜ読み込まれているの？（デフォルトで読み込む？）

**Comment by megane9988** [comment]
なぞですね。。
